In [32]:
import numpy as np
import pandas as pd

In [33]:
# import requests
# import zipfile
# import io

# # URL of the API endpoint that provides the zip file
# api_url = "https://api.data.gov.my/gtfs-static/prasarana?category=rapid-bus-penang"

# try:
#     # Make a GET request to the API
#     response = requests.get(api_url)

#     # Check if the request was successful (status code 200)
#     if response.status_code == 200:
#         # Open the zip file from the response content
#         with zipfile.ZipFile(io.BytesIO(response.content), 'r') as zip_ref:
#             # Extract all contents to a directory
#             zip_ref.extractall("rapidbuspenang-data")
#         print("Data extracted successfully.")
#     else:
#         print("Failed to retrieve data. Status code:", response.status_code)
# except Exception as e:
#     print("An error occurred:", e)

In [34]:
# pip install gtfs-realtime-bindings pandas requests
from google.transit import gtfs_realtime_pb2
from google.protobuf.json_format import MessageToDict
import pandas as pd
from requests import get
 
# Sample GTFS-R URL from Malaysia's Open API
URL = 'https://api.data.gov.my/gtfs-realtime/vehicle-position/prasarana?category=rapid-bus-penang'
# Parse the GTFS Realtime feed
feed = gtfs_realtime_pb2.FeedMessage()
response = get(URL)
feed.ParseFromString(response.content)
 
# Extract and print vehicle position information
vehicle_positions = [MessageToDict(entity.vehicle) for entity in feed.entity]
print(f'Total vehicles: {len(vehicle_positions)}')
df = pd.json_normalize(vehicle_positions)
print(df.head())

Total vehicles: 129
    timestamp                    trip.tripId trip.routeId  position.latitude  \
0  1708317488  30000005_1000000806_113000_01          201           5.404230
1  1708317498  30000041_1000000928_115000_02          709           5.371545
2  1708317498  30000001_1000000756_121500_01          101           5.474853
3  1708317487  30000038_1000000920_123000_02          703           5.403896
4  1708317496  30000014_1000000959_113000_01          304           5.396736

   position.longitude  position.bearing vehicle.id vehicle.licensePlate  \
0           100.28526              13.0    PLT2701              PLT2701
1           100.44017              89.0    PJG4327              PJG4327
2           100.27667             117.0    PLA7470              PLA7470
3           100.36606             192.0    PJJ6067              PJJ6067
4           100.30346              14.0    PKX3342              PKX3342

   position.speed
0             NaN
1            42.0
2            14.0
3            53.0
4             1.0

In [35]:
df

,timestamp,trip.tripId,trip.routeId,position.latitude,position.longitude,position.bearing,vehicle.id,vehicle.licensePlate,position.speed
0,1708317488,30000005_1000000806_113000_01,201,5.404230,100.285260,13.0,PLT2701,PLT2701,NaN
1,1708317498,30000041_1000000928_115000_02,709,5.371545,100.440170,89.0,PJG4327,PJG4327,42.0
2,1708317498,30000001_1000000756_121500_01,101,5.474853,100.276670,117.0,PLA7470,PLA7470,14.0
3,1708317487,30000038_1000000920_123000_02,703,5.403896,100.366060,192.0,PJJ6067,PJJ6067,53.0
4,1708317496,30000014_1000000959_113000_01,304,5.396736,100.303460,14.0,PKX3342,PKX3342,1.0
...,...,...,...,...,...,...,...,...,...
124,1708317485,30000001_1000000756_114500_01,101,5.432579,100.309390,86.0,PLL7535,PLL7535,25.0
125,1708317484,30000005_1000000806_115700_01,201,5.409505,100.293396,30.0,PJJ3296,PJJ3296,21.0
126,1708317482,30000020_1000000898_103000_01,401E,5.416278,100.343920,207.0,PLA2935,PLA2935,NaN
127,1708317493,30000089_1000000915_121000_01,613,5.464457,100.452680,227.0,PLA2891,PLA2891,43.0
128,1708317487,30000026_1000000902_123000_02,601,5.396299,100.366480,161.0,PLV2893,PLV2893,37.0

In [36]:
df['timestamp'] = pd.to_datetime(df['timestamp'],unit='s')

C:\Users\nasuha.imanina\AppData\Local\Temp\ipykernel_9868\20987537.py:1: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df['timestamp'] = pd.to_datetime(df['timestamp'],unit='s')

In [37]:
trip = pd.read_csv('rapidbuspenang-data/trips.txt')
shape = pd.read_csv('rapidbuspenang-data/shapes.txt')
stoptime = pd.read_csv('rapidbuspenang-data/stop_times.txt')
route = pd.read_csv('rapidbuspenang-data/routes.txt')
stop = pd.read_csv('rapidbuspenang-data/stops.txt')

In [38]:
# trip
# shape

In [39]:
newdata = pd.concat([df,trip],axis=1,join='inner')
newdata

,timestamp,trip.tripId,trip.routeId,position.latitude,position.longitude,position.bearing,vehicle.id,vehicle.licensePlate,position.speed,route_id,service_id,trip_id,trip_headsign,direction_id,shape_id
0,2024-02-19 04:37:20,30000005_1000000806_113000_01,201,5.404230,100.285260,13.0,PLT2701,PLT2701,NaN,30000024,23092501,230925010184S4,BALIK PULAU - JETI,0,1000000854
1,2024-02-19 04:37:20,30000041_1000000928_115000_02,709,5.371545,100.440170,89.0,PJG4327,PJG4327,42.0,30000002,23092501,230925010027S6,AIRPORT-TLK.BAHANG,0,1000000856
2,2024-02-19 04:37:20,30000001_1000000756_121500_01,101,5.474853,100.276670,117.0,PLA7470,PLA7470,14.0,30000002,23092502,230925020032S7,AIRPORT-TLK.BAHANG,0,1000000856
3,2024-02-19 04:37:20,30000038_1000000920_123000_02,703,5.403896,100.366060,192.0,PJJ6067,PJJ6067,53.0,30000001,23092502,230925020017S8,TLK.BAHANG-JETI,1,1000000756
4,2024-02-19 04:37:20,30000014_1000000959_113000_01,304,5.396736,100.303460,14.0,PKX3342,PKX3342,1.0,30000001,23092502,230925020017S4,TLK.BAHANG-JETI,1,1000000756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,2024-02-19 04:37:20,30000001_1000000756_114500_01,101,5.432579,100.309390,86.0,PLL7535,PLL7535,25.0,30000013,23092502,230925020129S3,BKT.GEDUNG - JETI,1,1000000765
125,2024-02-19 04:37:20,30000005_1000000806_115700_01,201,5.409505,100.293396,30.0,PJJ3296,PJJ3296,21.0,30000013,23092502,230925020126S6,BKT.GEDUNG - JETI,1,1000000765
126,2024-02-19 04:37:20,30000020_1000000898_103000_01,401E,5.416278,100.343920,207.0,PLA2935,PLA2935,NaN,30000013,23092501,230925010125S7,JETI - BUKIT GEDUNG,0,1000000835
127,2024-02-19 04:37:20,30000089_1000000915_121000_01,613,5.464457,100.452680,227.0,PLA2891,PLA2891,43.0,30000013,23092502,230925020132S3,JETI - BUKIT GEDUNG,0,1000000835
128,2024-02-19 04:37:20,30000026_1000000902_123000_02,601,5.396299,100.366480,161.0,PLV2893,PLV2893,37.0,30000013,23092502,230925020127S7,JETI - BUKIT GEDUNG,0,1000000835

In [40]:
newdata = pd.concat([newdata,shape],axis=1, join='inner')
newdata

,timestamp,trip.tripId,trip.routeId,position.latitude,position.longitude,position.bearing,vehicle.id,vehicle.licensePlate,position.speed,route_id,service_id,trip_id,trip_headsign,direction_id,shape_id,shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,shape_dist_traveled
0,2024-02-19 04:37:20,30000005_1000000806_113000_01,201,5.404230,100.285260,13.0,PLT2701,PLT2701,NaN,30000024,23092501,230925010184S4,BALIK PULAU - JETI,0,1000000854,1000000756,5.45785,100.21487,1,0.000000
1,2024-02-19 04:37:20,30000041_1000000928_115000_02,709,5.371545,100.440170,89.0,PJG4327,PJG4327,42.0,30000002,23092501,230925010027S6,AIRPORT-TLK.BAHANG,0,1000000856,1000000756,5.45795,100.21490,2,0.012000
2,2024-02-19 04:37:20,30000001_1000000756_121500_01,101,5.474853,100.276670,117.0,PLA7470,PLA7470,14.0,30000002,23092502,230925020032S7,AIRPORT-TLK.BAHANG,0,1000000856,1000000756,5.45827,100.21544,3,0.082000
3,2024-02-19 04:37:20,30000038_1000000920_123000_02,703,5.403896,100.366060,192.0,PJJ6067,PJJ6067,53.0,30000001,23092502,230925020017S8,TLK.BAHANG-JETI,1,1000000756,1000000756,5.45878,100.21617,4,0.181000
4,2024-02-19 04:37:20,30000014_1000000959_113000_01,304,5.396736,100.303460,14.0,PKX3342,PKX3342,1.0,30000001,23092502,230925020017S4,TLK.BAHANG-JETI,1,1000000756,1000000756,5.45938,100.21718,5,0.311000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,2024-02-19 04:37:20,30000001_1000000756_114500_01,101,5.432579,100.309390,86.0,PLL7535,PLL7535,25.0,30000013,23092502,230925020129S3,BKT.GEDUNG - JETI,1,1000000765,1000000756,5.48078,100.25625,125,6.199600
125,2024-02-19 04:37:20,30000005_1000000806_115700_01,201,5.409505,100.293396,30.0,PJJ3296,PJJ3296,21.0,30000013,23092502,230925020126S6,BKT.GEDUNG - JETI,1,1000000765,1000000756,5.48101,100.25658,126,6.244800
126,2024-02-19 04:37:20,30000020_1000000898_103000_01,401E,5.416278,100.343920,207.0,PLA2935,PLA2935,NaN,30000013,23092501,230925010125S7,JETI - BUKIT GEDUNG,0,1000000835,1000000756,5.48108,100.25689,127,6.279800
127,2024-02-19 04:37:20,30000089_1000000915_121000_01,613,5.464457,100.452680,227.0,PLA2891,PLA2891,43.0,30000013,23092502,230925020132S3,JETI - BUKIT GEDUNG,0,1000000835,1000000756,5.48115,100.25748,128,6.345799
128,2024-02-19 04:37:20,30000026_1000000902_123000_02,601,5.396299,100.366480,161.0,PLV2893,PLV2893,37.0,30000013,23092502,230925020127S7,JETI - BUKIT GEDUNG,0,1000000835,1000000756,5.48137,100.25828,129,6.437799

In [41]:
newdata = pd.concat([newdata,stoptime],axis=1, join='inner')
newdata

,timestamp,trip.tripId,trip.routeId,position.latitude,position.longitude,position.bearing,vehicle.id,vehicle.licensePlate,position.speed,route_id,...,shape_pt_lon,shape_pt_sequence,shape_dist_traveled,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,shape_dist_traveled
0,2024-02-19 04:37:20,30000005_1000000806_113000_01,201,5.404230,100.285260,13.0,PLT2701,PLT2701,NaN,30000024,...,100.21487,1,0.000000,230925010004S10,19:50:00,19:50:00,12002114,1,JETI - TELUK BAHANG,0.050556
1,2024-02-19 04:37:20,30000041_1000000928_115000_02,709,5.371545,100.440170,89.0,PJG4327,PJG4327,42.0,30000002,...,100.21490,2,0.012000,230925010004S10,19:50:37,19:50:37,12000007,2,JETI - TELUK BAHANG,0.244751
2,2024-02-19 04:37:20,30000001_1000000756_121500_01,101,5.474853,100.276670,117.0,PLA7470,PLA7470,14.0,30000002,...,100.21544,3,0.082000,230925010004S10,19:51:28,19:51:28,12001916,3,JETI - TELUK BAHANG,0.511194
3,2024-02-19 04:37:20,30000038_1000000920_123000_02,703,5.403896,100.366060,192.0,PJJ6067,PJJ6067,53.0,30000001,...,100.21617,4,0.181000,230925010004S10,19:52:13,19:52:13,12001918,4,JETI - TELUK BAHANG,0.738600
4,2024-02-19 04:37:20,30000014_1000000959_113000_01,304,5.396736,100.303460,14.0,PKX3342,PKX3342,1.0,30000001,...,100.21718,5,0.311000,230925010004S10,19:52:48,19:52:48,12001920,5,JETI - TELUK BAHANG,0.918909
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,2024-02-19 04:37:20,30000001_1000000756_114500_01,101,5.432579,100.309390,86.0,PLL7535,PLL7535,25.0,30000013,...,100.25625,125,6.199600,230925010004S11,22:38:08,22:38:08,12000365,49,TLK.BAHANG-JETI,18.100551
125,2024-02-19 04:37:20,30000005_1000000806_115700_01,201,5.409505,100.293396,30.0,PJJ3296,PJJ3296,21.0,30000013,...,100.25658,126,6.244800,230925010004S11,22:38:56,22:38:56,12000363,50,TLK.BAHANG-JETI,18.396528
126,2024-02-19 04:37:20,30000020_1000000898_103000_01,401E,5.416278,100.343920,207.0,PLA2935,PLA2935,NaN,30000013,...,100.25689,127,6.279800,230925010004S11,22:39:27,22:39:27,12000362,51,TLK.BAHANG-JETI,18.585995
127,2024-02-19 04:37:20,30000089_1000000915_121000_01,613,5.464457,100.452680,227.0,PLA2891,PLA2891,43.0,30000013,...,100.25748,128,6.345799,230925010004S11,22:39:57,22:39:57,12000361,52,TLK.BAHANG-JETI,18.757227
128,2024-02-19 04:37:20,30000026_1000000902_123000_02,601,5.396299,100.366480,161.0,PLV2893,PLV2893,37.0,30000013,...,100.25828,129,6.437799,230925010004S11,22:41:19,22:41:19,12001084,53,TLK.BAHANG-JETI,19.271579

In [42]:
newdata = pd.concat([newdata,route],axis=1, join='outer')
newdata

,timestamp,trip.tripId,trip.routeId,position.latitude,position.longitude,position.bearing,vehicle.id,vehicle.licensePlate,position.speed,route_id,...,departure_time,stop_id,stop_sequence,stop_headsign,shape_dist_traveled,route_id,agency_id,route_short_name,route_long_name,route_type
0,2024-02-19 04:37:20,30000005_1000000806_113000_01,201,5.404230,100.285260,13.0,PLT2701,PLT2701,NaN,30000024,...,19:50:00,12002114,1,JETI - TELUK BAHANG,0.050556,30000009.0,NaN,NaN,206,3.0
1,2024-02-19 04:37:20,30000041_1000000928_115000_02,709,5.371545,100.440170,89.0,PJG4327,PJG4327,42.0,30000002,...,19:50:37,12000007,2,JETI - TELUK BAHANG,0.244751,30000019.0,NaN,NaN,401,3.0
2,2024-02-19 04:37:20,30000001_1000000756_121500_01,101,5.474853,100.276670,117.0,PLA7470,PLA7470,14.0,30000002,...,19:51:28,12001916,3,JETI - TELUK BAHANG,0.511194,30000040.0,NaN,NaN,708,3.0
3,2024-02-19 04:37:20,30000038_1000000920_123000_02,703,5.403896,100.366060,192.0,PJJ6067,PJJ6067,53.0,30000001,...,19:52:13,12001918,4,JETI - TELUK BAHANG,0.738600,30000089.0,NaN,NaN,613,3.0
4,2024-02-19 04:37:20,30000014_1000000959_113000_01,304,5.396736,100.303460,14.0,PKX3342,PKX3342,1.0,30000001,...,19:52:48,12001920,5,JETI - TELUK BAHANG,0.918909,30000051.0,NaN,NaN,CAT,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,2024-02-19 04:37:20,30000001_1000000756_114500_01,101,5.432579,100.309390,86.0,PLL7535,PLL7535,25.0,30000013,...,22:38:08,12000365,49,TLK.BAHANG-JETI,18.100551,NaN,NaN,NaN,NaN,NaN
125,2024-02-19 04:37:20,30000005_1000000806_115700_01,201,5.409505,100.293396,30.0,PJJ3296,PJJ3296,21.0,30000013,...,22:38:56,12000363,50,TLK.BAHANG-JETI,18.396528,NaN,NaN,NaN,NaN,NaN
126,2024-02-19 04:37:20,30000020_1000000898_103000_01,401E,5.416278,100.343920,207.0,PLA2935,PLA2935,NaN,30000013,...,22:39:27,12000362,51,TLK.BAHANG-JETI,18.585995,NaN,NaN,NaN,NaN,NaN
127,2024-02-19 04:37:20,30000089_1000000915_121000_01,613,5.464457,100.452680,227.0,PLA2891,PLA2891,43.0,30000013,...,22:39:57,12000361,52,TLK.BAHANG-JETI,18.757227,NaN,NaN,NaN,NaN,NaN
128,2024-02-19 04:37:20,30000026_1000000902_123000_02,601,5.396299,100.366480,161.0,PLV2893,PLV2893,37.0,30000013,...,22:41:19,12001084,53,TLK.BAHANG-JETI,19.271579,NaN,NaN,NaN,NaN,NaN

In [43]:
newdata = pd.concat([newdata,stop],axis=1, join='inner')
newdata

,timestamp,trip.tripId,trip.routeId,position.latitude,position.longitude,position.bearing,vehicle.id,vehicle.licensePlate,position.speed,route_id,...,route_id,agency_id,route_short_name,route_long_name,route_type,stop_id,stop_code,stop_name,stop_lat,stop_lon
0,2024-02-19 04:37:20,30000005_1000000806_113000_01,201,5.404230,100.285260,13.0,PLT2701,PLT2701,NaN,30000024,...,30000009.0,NaN,NaN,206,3.0,12000148,I0Z0148,Taman Seri Indah,5.34345,100.22733
1,2024-02-19 04:37:20,30000041_1000000928_115000_02,709,5.371545,100.440170,89.0,PJG4327,PJG4327,42.0,30000002,...,30000019.0,NaN,NaN,401,3.0,12002280,ICT0001,SK Kongsi,5.34657,100.23050
2,2024-02-19 04:37:20,30000001_1000000756_121500_01,101,5.474853,100.276670,117.0,PLA7470,PLA7470,14.0,30000002,...,30000040.0,NaN,NaN,708,3.0,12000059,I0Q0059,Pejabat Pos Ayer Itam,5.40410,100.28008
3,2024-02-19 04:37:20,30000038_1000000920_123000_02,703,5.403896,100.366060,192.0,PJJ6067,PJJ6067,53.0,30000001,...,30000089.0,NaN,NaN,613,3.0,12001060,IEV1060,Komtar Utara,5.41513,100.32899
4,2024-02-19 04:37:20,30000014_1000000959_113000_01,304,5.396736,100.303460,14.0,PKX3342,PKX3342,1.0,30000001,...,30000051.0,NaN,NaN,CAT,3.0,12001832,IIC1832,Wisma MCA,5.41841,100.32954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,2024-02-19 04:37:20,30000001_1000000756_114500_01,101,5.432579,100.309390,86.0,PLL7535,PLL7535,25.0,30000013,...,NaN,NaN,NaN,NaN,NaN,12001342,MFU1342,Pusat Perniagaan Raja Uda,5.41782,100.38021
125,2024-02-19 04:37:20,30000005_1000000806_115700_01,201,5.409505,100.293396,30.0,PJJ3296,PJJ3296,21.0,30000013,...,NaN,NaN,NaN,NaN,NaN,12001595,MHB1595,Pekan Maklom,5.45056,100.40128
126,2024-02-19 04:37:20,30000020_1000000898_103000_01,401E,5.416278,100.343920,207.0,PLA2935,PLA2935,NaN,30000013,...,NaN,NaN,NaN,NaN,NaN,12001508,MGX1508,Pusat Perniagaan Desa Murni,5.43710,100.43021
127,2024-02-19 04:37:20,30000089_1000000915_121000_01,613,5.464457,100.452680,227.0,PLA2891,PLA2891,43.0,30000013,...,NaN,NaN,NaN,NaN,NaN,12000111,M0W0111,Taman Sentral,5.42532,100.39706
128,2024-02-19 04:37:20,30000026_1000000902_123000_02,601,5.396299,100.366480,161.0,PLV2893,PLV2893,37.0,30000013,...,NaN,NaN,NaN,NaN,NaN,12002032,MKA2032,Evergreen Paper,5.41941,100.39243

In [44]:
newdata

,timestamp,trip.tripId,trip.routeId,position.latitude,position.longitude,position.bearing,vehicle.id,vehicle.licensePlate,position.speed,route_id,...,route_id,agency_id,route_short_name,route_long_name,route_type,stop_id,stop_code,stop_name,stop_lat,stop_lon
0,2024-02-19 04:37:20,30000005_1000000806_113000_01,201,5.404230,100.285260,13.0,PLT2701,PLT2701,NaN,30000024,...,30000009.0,NaN,NaN,206,3.0,12000148,I0Z0148,Taman Seri Indah,5.34345,100.22733
1,2024-02-19 04:37:20,30000041_1000000928_115000_02,709,5.371545,100.440170,89.0,PJG4327,PJG4327,42.0,30000002,...,30000019.0,NaN,NaN,401,3.0,12002280,ICT0001,SK Kongsi,5.34657,100.23050
2,2024-02-19 04:37:20,30000001_1000000756_121500_01,101,5.474853,100.276670,117.0,PLA7470,PLA7470,14.0,30000002,...,30000040.0,NaN,NaN,708,3.0,12000059,I0Q0059,Pejabat Pos Ayer Itam,5.40410,100.28008
3,2024-02-19 04:37:20,30000038_1000000920_123000_02,703,5.403896,100.366060,192.0,PJJ6067,PJJ6067,53.0,30000001,...,30000089.0,NaN,NaN,613,3.0,12001060,IEV1060,Komtar Utara,5.41513,100.32899
4,2024-02-19 04:37:20,30000014_1000000959_113000_01,304,5.396736,100.303460,14.0,PKX3342,PKX3342,1.0,30000001,...,30000051.0,NaN,NaN,CAT,3.0,12001832,IIC1832,Wisma MCA,5.41841,100.32954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,2024-02-19 04:37:20,30000001_1000000756_114500_01,101,5.432579,100.309390,86.0,PLL7535,PLL7535,25.0,30000013,...,NaN,NaN,NaN,NaN,NaN,12001342,MFU1342,Pusat Perniagaan Raja Uda,5.41782,100.38021
125,2024-02-19 04:37:20,30000005_1000000806_115700_01,201,5.409505,100.293396,30.0,PJJ3296,PJJ3296,21.0,30000013,...,NaN,NaN,NaN,NaN,NaN,12001595,MHB1595,Pekan Maklom,5.45056,100.40128
126,2024-02-19 04:37:20,30000020_1000000898_103000_01,401E,5.416278,100.343920,207.0,PLA2935,PLA2935,NaN,30000013,...,NaN,NaN,NaN,NaN,NaN,12001508,MGX1508,Pusat Perniagaan Desa Murni,5.43710,100.43021
127,2024-02-19 04:37:20,30000089_1000000915_121000_01,613,5.464457,100.452680,227.0,PLA2891,PLA2891,43.0,30000013,...,NaN,NaN,NaN,NaN,NaN,12000111,M0W0111,Taman Sentral,5.42532,100.39706
128,2024-02-19 04:37:20,30000026_1000000902_123000_02,601,5.396299,100.366480,161.0,PLV2893,PLV2893,37.0,30000013,...,NaN,NaN,NaN,NaN,NaN,12002032,MKA2032,Evergreen Paper,5.41941,100.39243

In [51]:
newdata['timestamp'] = newdata['timestamp'].astype(str)

In [71]:
from keplergl import KeplerGl
from datetime import datetime
import json

# Assuming the 'arrival_time' column represents the time dimension
# You can also use 'departure_time' or any other time-related column from your GTFS data

# Create a Kepler.gl map
map_1 = KeplerGl()

# Add data to the map
# map_1.add_data(data=station[station['coordinates']], name='coordinate')
map_1.add_data(data=newdata, name='rapid rail kl')

# Configure the Kepler.gl map to animate based on the timestamp column
map_1.config = {
    'version': 'v1',
    'config': {
         'mapState': {
            'latitude': 5.425300,
            'longitude': 100.312386,
            'zoom' : 11
        }
    }
}

# Visualize the animated data within Kepler.gl

# map_1
# You can further configure the map interactively in the Jupyter Notebook environment

# If you want to save the map configuration for later use or share it with others
# you can save it as a JSON file
# config = map_1.config

# configsavepenang = json.dumps(config, default=str)
# print(configsavepenang)
# with open('keplergl_config.json', 'w') as f:
#     f.write(configsavepenang)

# # You can also export the map as an HTML file
# map_1.save_to_html(file_name='rapidbuspenang.html')
map_1

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter

c:\Users\nasuha.imanina\Documents\railway-test\venv\lib\site-packages\keplergl\keplergl.py:22: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  return df.to_dict('split')
c:\Users\nasuha.imanina\Documents\railway-test\venv\lib\site-packages\jupyter_client\session.py:721: UserWarning: Message serialization failed with:
Out of range float values are not JSON compliant
Supporting this message is deprecated in jupyter-client 7, please make sure your message is JSON-compliant
  content = self.pack(content)

KeplerGl(config={'version': 'v1', 'config': {'mapState': {'latitude': 5.4253, 'longitude': 100.312386, 'zoom':â€¦

In [72]:
config = map_1.config

In [73]:
print(config)

{'version': 'v1', 'config': {'visState': {'filters': [], 'layers': [{'id': 'jwbtqzf', 'type': 'point', 'config': {'dataId': 'rapid rail kl', 'label': 'position', 'color': [248, 149, 112], 'highlightColor': [252, 242, 26, 255], 'columns': {'lat': 'position.latitude', 'lng': 'position.longitude', 'altitude': None}, 'isVisible': True, 'visConfig': {'radius': 10, 'fixedRadius': False, 'opacity': 0.8, 'outline': False, 'thickness': 2, 'strokeColor': None, 'colorRange': {'name': 'Global Warming', 'type': 'sequential', 'category': 'Uber', 'colors': ['#5A1846', '#900C3F', '#C70039', '#E3611C', '#F1920E', '#FFC300']}, 'strokeColorRange': {'name': 'Global Warming', 'type': 'sequential', 'category': 'Uber', 'colors': ['#5A1846', '#900C3F', '#C70039', '#E3611C', '#F1920E', '#FFC300']}, 'radiusRange': [0, 50], 'filled': True}, 'hidden': False, 'textLabel': [{'field': None, 'color': [255, 255, 255], 'size': 18, 'offset': [0, 0], 'anchor': 'start', 'alignment': 'center'}]}, 'visualChannels': {'colorField': {'name': 'shape_dist_traveled', 'type': 'real'}, 'colorScale': 'quantile', 'strokeColorField': None, 'strokeColorScale': 'quantile', 'sizeField': None, 'sizeScale': 'linear'}}, {'id': 'x4du1kn', 'type': 'point', 'config': {'dataId': 'rapid rail kl', 'label': 'shape pt', 'color': [130, 154, 227], 'highlightColor': [252, 242, 26, 255], 'columns': {'lat': 'shape_pt_lat', 'lng': 'shape_pt_lon', 'altitude': None}, 'isVisible': False, 'visConfig': {'radius': 10, 'fixedRadius': False, 'opacity': 0.8, 'outline': False, 'thickness': 2, 'strokeColor': None, 'colorRange': {'name': 'Global Warming', 'type': 'sequential', 'category': 'Uber', 'colors': ['#5A1846', '#900C3F', '#C70039', '#E3611C', '#F1920E', '#FFC300']}, 'strokeColorRange': {'name': 'Global Warming', 'type': 'sequential', 'category': 'Uber', 'colors': ['#5A1846', '#900C3F', '#C70039', '#E3611C', '#F1920E', '#FFC300']}, 'radiusRange': [0, 50], 'filled': True}, 'hidden': False, 'textLabel': [{'field': None, 'color': [255, 255, 255], 'size': 18, 'offset': [0, 0], 'anchor': 'start', 'alignment': 'center'}]}, 'visualChannels': {'colorField': {'name': 'shape_dist_traveled', 'type': 'real'}, 'colorScale': 'quantile', 'strokeColorField': None, 'strokeColorScale': 'quantile', 'sizeField': None, 'sizeScale': 'linear'}}, {'id': 'a4wpyt9', 'type': 'point', 'config': {'dataId': 'rapid rail kl', 'label': 'stop', 'color': [231, 159, 213], 'highlightColor': [252, 242, 26, 255], 'columns': {'lat': 'stop_lat', 'lng': 'stop_lon', 'altitude': None}, 'isVisible': True, 'visConfig': {'radius': 10, 'fixedRadius': False, 'opacity': 0.8, 'outline': False, 'thickness': 2, 'strokeColor': None, 'colorRange': {'name': 'Global Warming', 'type': 'sequential', 'category': 'Uber', 'colors': ['#5A1846', '#900C3F', '#C70039', '#E3611C', '#F1920E', '#FFC300']}, 'strokeColorRange': {'name': 'Global Warming', 'type': 'sequential', 'category': 'Uber', 'colors': ['#5A1846', '#900C3F', '#C70039', '#E3611C', '#F1920E', '#FFC300']}, 'radiusRange': [0, 50], 'filled': True}, 'hidden': False, 'textLabel': [{'field': None, 'color': [255, 255, 255], 'size': 18, 'offset': [0, 0], 'anchor': 'start', 'alignment': 'center'}]}, 'visualChannels': {'colorField': {'name': 'shape_dist_traveled', 'type': 'real'}, 'colorScale': 'quantile', 'strokeColorField': None, 'strokeColorScale': 'quantile', 'sizeField': None, 'sizeScale': 'linear'}}, {'id': '8lyhwyj', 'type': 'arc', 'config': {'dataId': 'rapid rail kl', 'label': 'position -> shape pt arc', 'color': [146, 38, 198], 'highlightColor': [252, 242, 26, 255], 'columns': {'lat0': 'position.latitude', 'lng0': 'position.longitude', 'lat1': 'shape_pt_lat', 'lng1': 'shape_pt_lon'}, 'isVisible': True, 'visConfig': {'opacity': 0.8, 'thickness': 2, 'colorRange': {'name': 'Global Warming', 'type': 'sequential', 'category': 'Uber', 'colors': ['#5A1846', '#900C3F', '#C70039', '#E3611C', '#F1920E', '#FFC300']}, 'sizeRange': [0, 10], 'targetColor': None}, 'hidden': False, 'textLabel': [{'field': None, 'color': [255, 255, 255], 'size': 18, 'offset': [0, 0], 'anchor': 'start', 'alignment': 'center'}]}, 'visualChannels': {'colorField': None, 'colorScale': 'quantile', 'sizeField': None, 'sizeScale': 'linear'}}, {'id': 'okik9gf', 'type': 'line', 'config': {'dataId': 'rapid rail kl', 'label': 'position -> shape pt line', 'color': [30, 150, 190], 'highlightColor': [252, 242, 26, 255], 'columns': {'lat0': 'position.latitude', 'lng0': 'position.longitude', 'alt0': None, 'lat1': 'shape_pt_lat', 'lng1': 'shape_pt_lon', 'alt1': None}, 'isVisible': False, 'visConfig': {'opacity': 0.8, 'thickness': 2, 'colorRange': {'name': 'Global Warming', 'type': 'sequential', 'category': 'Uber', 'colors': ['#5A1846', '#900C3F', '#C70039', '#E3611C', '#F1920E', '#FFC300']}, 'sizeRange': [0, 10], 'targetColor': None, 'elevationScale': 1}, 'hidden': False, 'textLabel': [{'field': None, 'color': [255, 255, 255], 'size': 18, 'offset': [0, 0], 'anchor': 'start', 'alignment': 'center'}]}, 'visualChannels': {'colorField': None, 'colorScale': 'quantile', 'sizeField': None, 'sizeScale': 'linear'}}], 'interactionConfig': {'tooltip': {'fieldsToShow': {'rapid rail kl': [{'name': 'timestamp', 'format': None}, {'name': 'vehicle.licensePlate', 'format': None}, {'name': 'trip_headsign', 'format': None}, {'name': 'stop_name', 'format': None}, {'name': 'route_short_name', 'format': None}, {'name': 'route_long_name', 'format': None}, {'name': 'arrival_time', 'format': None}]}, 'compareMode': False, 'compareType': 'absolute', 'enabled': True}, 'brush': {'size': 0.5, 'enabled': False}, 'geocoder': {'enabled': False}, 'coordinate': {'enabled': False}}, 'layerBlending': 'normal', 'splitMaps': [], 'animationConfig': {'currentTime': None, 'speed': 1}}, 'mapState': {'bearing': 0, 'dragRotate': False, 'latitude': 5.408535182792562, 'longitude': 100.39694984904901, 'pitch': 0, 'zoom': 10.296140092997826, 'isSplit': False}, 'mapStyle': {'styleType': 'dark', 'topLayerGroups': {}, 'visibleLayerGroups': {'label': True, 'road': True, 'border': False, 'building': True, 'water': True, 'land': True, '3d building': False}, 'threeDBuildingColor': [9.665468314072013, 17.18305478057247, 31.1442867897876], 'mapStyles': {}}}}

In [74]:
configsavepenang = json.dumps(config, default=str)
print(configsavepenang)
with open('keplergl_config-penang.json', 'w') as f:
    f.write(configsavepenang)

# You can also export the map as an HTML file
map_1.save_to_html(file_name='rapidbuspenang.html')

{"version": "v1", "config": {"visState": {"filters": [], "layers": [{"id": "jwbtqzf", "type": "point", "config": {"dataId": "rapid rail kl", "label": "position", "color": [248, 149, 112], "highlightColor": [252, 242, 26, 255], "columns": {"lat": "position.latitude", "lng": "position.longitude", "altitude": null}, "isVisible": true, "visConfig": {"radius": 10, "fixedRadius": false, "opacity": 0.8, "outline": false, "thickness": 2, "strokeColor": null, "colorRange": {"name": "Global Warming", "type": "sequential", "category": "Uber", "colors": ["#5A1846", "#900C3F", "#C70039", "#E3611C", "#F1920E", "#FFC300"]}, "strokeColorRange": {"name": "Global Warming", "type": "sequential", "category": "Uber", "colors": ["#5A1846", "#900C3F", "#C70039", "#E3611C", "#F1920E", "#FFC300"]}, "radiusRange": [0, 50], "filled": true}, "hidden": false, "textLabel": [{"field": null, "color": [255, 255, 255], "size": 18, "offset": [0, 0], "anchor": "start", "alignment": "center"}]}, "visualChannels": {"colorField": {"name": "shape_dist_traveled", "type": "real"}, "colorScale": "quantile", "strokeColorField": null, "strokeColorScale": "quantile", "sizeField": null, "sizeScale": "linear"}}, {"id": "x4du1kn", "type": "point", "config": {"dataId": "rapid rail kl", "label": "shape pt", "color": [130, 154, 227], "highlightColor": [252, 242, 26, 255], "columns": {"lat": "shape_pt_lat", "lng": "shape_pt_lon", "altitude": null}, "isVisible": false, "visConfig": {"radius": 10, "fixedRadius": false, "opacity": 0.8, "outline": false, "thickness": 2, "strokeColor": null, "colorRange": {"name": "Global Warming", "type": "sequential", "category": "Uber", "colors": ["#5A1846", "#900C3F", "#C70039", "#E3611C", "#F1920E", "#FFC300"]}, "strokeColorRange": {"name": "Global Warming", "type": "sequential", "category": "Uber", "colors": ["#5A1846", "#900C3F", "#C70039", "#E3611C", "#F1920E", "#FFC300"]}, "radiusRange": [0, 50], "filled": true}, "hidden": false, "textLabel": [{"field": null, "color": [255, 255, 255], "size": 18, "offset": [0, 0], "anchor": "start", "alignment": "center"}]}, "visualChannels": {"colorField": {"name": "shape_dist_traveled", "type": "real"}, "colorScale": "quantile", "strokeColorField": null, "strokeColorScale": "quantile", "sizeField": null, "sizeScale": "linear"}}, {"id": "a4wpyt9", "type": "point", "config": {"dataId": "rapid rail kl", "label": "stop", "color": [231, 159, 213], "highlightColor": [252, 242, 26, 255], "columns": {"lat": "stop_lat", "lng": "stop_lon", "altitude": null}, "isVisible": true, "visConfig": {"radius": 10, "fixedRadius": false, "opacity": 0.8, "outline": false, "thickness": 2, "strokeColor": null, "colorRange": {"name": "Global Warming", "type": "sequential", "category": "Uber", "colors": ["#5A1846", "#900C3F", "#C70039", "#E3611C", "#F1920E", "#FFC300"]}, "strokeColorRange": {"name": "Global Warming", "type": "sequential", "category": "Uber", "colors": ["#5A1846", "#900C3F", "#C70039", "#E3611C", "#F1920E", "#FFC300"]}, "radiusRange": [0, 50], "filled": true}, "hidden": false, "textLabel": [{"field": null, "color": [255, 255, 255], "size": 18, "offset": [0, 0], "anchor": "start", "alignment": "center"}]}, "visualChannels": {"colorField": {"name": "shape_dist_traveled", "type": "real"}, "colorScale": "quantile", "strokeColorField": null, "strokeColorScale": "quantile", "sizeField": null, "sizeScale": "linear"}}, {"id": "8lyhwyj", "type": "arc", "config": {"dataId": "rapid rail kl", "label": "position -> shape pt arc", "color": [146, 38, 198], "highlightColor": [252, 242, 26, 255], "columns": {"lat0": "position.latitude", "lng0": "position.longitude", "lat1": "shape_pt_lat", "lng1": "shape_pt_lon"}, "isVisible": true, "visConfig": {"opacity": 0.8, "thickness": 2, "colorRange": {"name": "Global Warming", "type": "sequential", "category": "Uber", "colors": ["#5A1846", "#900C3F", "#C70039", "#E3611C", "#F1920E", "#FFC300"]}, "sizeRange": [0, 10], "targetColor": null}, "hidden": false, "textLabel": [{"field": null, "color": [255, 255, 255], "size": 18, "offset": [0, 0], "anchor": "start", "alignment": "center"}]}, "visualChannels": {"colorField": null, "colorScale": "quantile", "sizeField": null, "sizeScale": "linear"}}, {"id": "okik9gf", "type": "line", "config": {"dataId": "rapid rail kl", "label": "position -> shape pt line", "color": [30, 150, 190], "highlightColor": [252, 242, 26, 255], "columns": {"lat0": "position.latitude", "lng0": "position.longitude", "alt0": null, "lat1": "shape_pt_lat", "lng1": "shape_pt_lon", "alt1": null}, "isVisible": false, "visConfig": {"opacity": 0.8, "thickness": 2, "colorRange": {"name": "Global Warming", "type": "sequential", "category": "Uber", "colors": ["#5A1846", "#900C3F", "#C70039", "#E3611C", "#F1920E", "#FFC300"]}, "sizeRange": [0, 10], "targetColor": null, "elevationScale": 1}, "hidden": false, "textLabel": [{"field": null, "color": [255, 255, 255], "size": 18, "offset": [0, 0], "anchor": "start", "alignment": "center"}]}, "visualChannels": {"colorField": null, "colorScale": "quantile", "sizeField": null, "sizeScale": "linear"}}], "interactionConfig": {"tooltip": {"fieldsToShow": {"rapid rail kl": [{"name": "timestamp", "format": null}, {"name": "vehicle.licensePlate", "format": null}, {"name": "trip_headsign", "format": null}, {"name": "stop_name", "format": null}, {"name": "route_short_name", "format": null}, {"name": "route_long_name", "format": null}, {"name": "arrival_time", "format": null}]}, "compareMode": false, "compareType": "absolute", "enabled": true}, "brush": {"size": 0.5, "enabled": false}, "geocoder": {"enabled": false}, "coordinate": {"enabled": false}}, "layerBlending": "normal", "splitMaps": [], "animationConfig": {"currentTime": null, "speed": 1}}, "mapState": {"bearing": 0, "dragRotate": false, "latitude": 5.408535182792562, "longitude": 100.39694984904901, "pitch": 0, "zoom": 10.296140092997826, "isSplit": false}, "mapStyle": {"styleType": "dark", "topLayerGroups": {}, "visibleLayerGroups": {"label": true, "road": true, "border": false, "building": true, "water": true, "land": true, "3d building": false}, "threeDBuildingColor": [9.665468314072013, 17.18305478057247, 31.1442867897876], "mapStyles": {}}}}
Map saved to rapidbuspenang.html!